[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  YARN_VERSION = "1.22.0"
  NODE_VERSION = "13.5.0"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_OPTIONS = "--max_old_space_size=4096"